const QUESTIONS = [
  {cat:'Appliquer une remise', text:'Un article coûte 240 € HT. Une remise de 15 % est accordée. Quel est le prix après remise ?', decimals:2, answers:[{label:'Prix remisé (€)', value:204, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un téléviseur est affiché à 899 €. Une remise de 30 % est accordée. Calculer le prix après remise.', decimals:2, answers:[{label:'Prix après remise (€)', value:629.30, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un grossiste accorde une remise de 8 % sur une commande de 3 500 €. Quel montant le client paie-t-il ?', decimals:2, answers:[{label:'Montant payé (€)', value:3220, suffix:'€'}]},
  {cat:'Coefficient de remise', text:'Quel coefficient multiplicateur applique-t-on pour une remise de 5 % ?', decimals:3, answers:[{label:'Coefficient', value:0.95, suffix:''}]},
  {cat:'Coefficient de remise', text:'Quel coefficient multiplicateur applique-t-on pour une remise de 12 % ?', decimals:3, answers:[{label:'Coefficient', value:0.88, suffix:''}]},
  {cat:'Coefficient de remise', text:'Quel coefficient multiplicateur applique-t-on pour une remise de 25 % ?', decimals:3, answers:[{label:'Coefficient', value:0.75, suffix:''}]},
  {cat:'Appliquer une remise', text:'Une paire de chaussures à 79,90 € bénéficie d\u2019une remise de 20 %. Quel est le nouveau prix ?', decimals:2, answers:[{label:'Nouveau prix (€)', value:63.92, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un manteau à 145 € est vendu avec 35 % de remise. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:94.25, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un ordinateur coûte 1 249 €. Le vendeur accorde 6 % de remise. Quel est le prix remisé ?', decimals:2, answers:[{label:'Prix remisé (€)', value:1174.06, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un lot de marchandises vaut 2 780 € HT. Une remise de 11 % est accordée. Quel est le prix après remise ?', decimals:2, answers:[{label:'Prix après remise (€)', value:2474.20, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Une commande de 425 € bénéficie de 18 % de remise. Quel est le montant à payer ?', decimals:2, answers:[{label:'Montant à payer (€)', value:348.50, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un canapé coûte 689 €. Il est soldé à -40 %. Quel est son prix soldé ?', decimals:2, answers:[{label:'Prix soldé (€)', value:413.40, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Une facture de 5 600 € HT reçoit une remise de 2,5 %. Quel est le montant après remise ?', decimals:2, answers:[{label:'Montant après remise (€)', value:5460, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un produit à 34,50 € obtient une remise de 10 %. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:31.05, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Un vélo est affiché 699 €. Une remise de 12 % est appliquée. Quel est le prix à payer ?', decimals:2, answers:[{label:'Prix à payer (€)', value:615.12, suffix:'€'}]},
  {cat:'Appliquer une remise', text:'Une imprimante coûte 159,99 €. Elle est remisée de 15 %. Quel est le prix remisé ?', decimals:2, answers:[{label:'Prix remisé (€)', value:135.99, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Calculer le montant de la remise sur un article à 560 € avec une remise de 12 %.', decimals:2, answers:[{label:'Montant de la remise (€)', value:67.20, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Un client achète pour 1 800 € HT de marchandises. Une remise de 7 % lui est accordée. Quel est le montant de l\u2019économie réalisée ?', decimals:2, answers:[{label:'Économie réalisée (€)', value:126, suffix:'€'}]},
  {cat:'Taux de remise', text:'Le montant d\u2019une remise est de 45 € pour un article à 300 €. Quel est le taux de remise accordé ?', decimals:2, answers:[{label:'Taux de remise (%)', value:15, suffix:'%'}]},
  {cat:'Montant d\u2019une remise', text:'Un article coûte 89 €. Il bénéficie d\u2019une remise de 5 %. Quel est le montant de la remise ?', decimals:2, answers:[{label:'Montant de la remise (€)', value:4.45, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Une commande de 2 450 € obtient une remise de 9 %. Quel est le montant de la remise ?', decimals:2, answers:[{label:'Montant de la remise (€)', value:220.50, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Un meuble à 1 150 € est soldé à -22 %. Quel est le montant de la réduction ?', decimals:2, answers:[{label:'Montant de la réduction (€)', value:253, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Un produit coûte 47,80 €. La remise est de 30 %. Calculer le montant de la remise.', decimals:2, answers:[{label:'Montant de la remise (€)', value:14.34, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Une facture de 980 € HT obtient une remise de 4 %. Quel est le montant de remise ?', decimals:2, answers:[{label:'Montant de remise (€)', value:39.20, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Un client économise 72 € sur un achat initial de 600 €. Quel est le taux de remise ?', decimals:2, answers:[{label:'Taux de remise (%)', value:12, suffix:'%'}]},
  {cat:'Montant d\u2019une remise', text:'Une remise de 16 % est accordée sur 375 €. Quel est le montant de la remise ?', decimals:2, answers:[{label:'Montant de la remise (€)', value:60, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Une boutique accorde 8,5 % de remise sur 720 €. Quel est le montant de remise ?', decimals:2, answers:[{label:'Montant de remise (€)', value:61.20, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Le prix catalogue est de 1 990 €. La remise est de 13 %. Combien représente la remise ?', decimals:2, answers:[{label:'Montant de la remise (€)', value:258.70, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Un article passe de 80 € à 68 €. Quel est le montant de la remise en euros ?', decimals:2, answers:[{label:'Montant de la remise (€)', value:12, suffix:'€'}]},
  {cat:'Montant d\u2019une remise', text:'Une remise de 31,50 € est accordée sur un prix de 210 €. Quel est le taux de remise ?', decimals:2, answers:[{label:'Taux de remise (%)', value:15, suffix:'%'}]},
  {cat:'HT vers TTC', text:'Un prestataire facture 450 € HT. La TVA est à 20 %. Quel montant TTC le client devra-t-il régler ?', decimals:2, answers:[{label:'Montant TTC (€)', value:540, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un produit alimentaire vaut 12,00 € HT. TVA applicable 5,5 %. Calculer le prix TTC.', decimals:2, answers:[{label:'Prix TTC (€)', value:12.66, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un hôtel facture une chambre 95 € HT avec TVA à 10 %. Quel est le montant TTC de la nuit ?', decimals:2, answers:[{label:'Montant TTC (€)', value:104.50, suffix:'€'}]},
  {cat:'Coefficient TVA', text:'Calculer le coefficient de TVA pour un taux de 2,1 %.', decimals:3, answers:[{label:'Coefficient TVA', value:1.021, suffix:''}]},
  {cat:'Coefficient TVA', text:'Calculer le coefficient de TVA pour un taux de 5,5 %.', decimals:3, answers:[{label:'Coefficient TVA', value:1.055, suffix:''}]},
  {cat:'Coefficient TVA', text:'Calculer le coefficient de TVA pour un taux de 10 %.', decimals:3, answers:[{label:'Coefficient TVA', value:1.10, suffix:''}]},
  {cat:'Coefficient TVA', text:'Calculer le coefficient de TVA pour un taux de 20 %.', decimals:3, answers:[{label:'Coefficient TVA', value:1.20, suffix:''}]},
  {cat:'HT vers TTC', text:'Un article coûte 79 € HT. TVA 20 %. Quel est le prix TTC ?', decimals:2, answers:[{label:'Prix TTC (€)', value:94.80, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un repas est facturé 28 € HT avec TVA à 10 %. Quel est le TTC ?', decimals:2, answers:[{label:'TTC (€)', value:30.80, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un livre vaut 18,50 € HT avec TVA à 5,5 %. Quel est son prix TTC ?', decimals:2, answers:[{label:'Prix TTC (€)', value:19.52, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Une prestation vaut 1 250 € HT. TVA 20 %. Calculer le TTC.', decimals:2, answers:[{label:'TTC (€)', value:1500, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un devis affiche 3 640 € HT avec TVA à 20 %. Calculer le montant TTC.', decimals:2, answers:[{label:'Montant TTC (€)', value:4368, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Une nuitée est facturée 62 € HT avec TVA à 10 %. Calculer le prix TTC.', decimals:2, answers:[{label:'Prix TTC (€)', value:68.20, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un produit alimentaire coûte 4,70 € HT. TVA 5,5 %. Calculer le TTC.', decimals:2, answers:[{label:'TTC (€)', value:4.96, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Une réparation est facturée 289 € HT avec TVA à 20 %. Calculer le TTC.', decimals:2, answers:[{label:'TTC (€)', value:346.80, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Un abonnement est vendu 39,90 € HT avec TVA à 20 %. Quel est le prix TTC ?', decimals:2, answers:[{label:'Prix TTC (€)', value:47.88, suffix:'€'}]},
  {cat:'HT vers TTC', text:'Une commande alimentaire vaut 156 € HT avec TVA à 5,5 %. Calculer le TTC.', decimals:2, answers:[{label:'TTC (€)', value:164.58, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Une facture affiche 360 € TTC avec une TVA à 20 %. Retrouver le montant HT et le montant de TVA.', decimals:2, answers:[{label:'Montant HT (€)', value:300, suffix:'€'}, {label:'Montant de TVA (€)', value:60, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un ticket indique 21,30 € TTC pour un produit alimentaire avec TVA 5,5 %. Quel est le prix HT ?', decimals:2, answers:[{label:'Prix HT (€)', value:20.19, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un devis s\u2019élève à 1 140 € TTC avec TVA 20 %. Calculer le montant HT.', decimals:2, answers:[{label:'Montant HT (€)', value:950, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un produit est vendu 96 € TTC avec TVA 20 %. Quel est son prix HT ?', decimals:2, answers:[{label:'Prix HT (€)', value:80, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un repas coûte 44 € TTC avec TVA 10 %. Calculer le HT.', decimals:2, answers:[{label:'Prix HT (€)', value:40, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un article alimentaire est vendu 6,33 € TTC avec TVA 5,5 %. Calculer le HT.', decimals:2, answers:[{label:'Prix HT (€)', value:6, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Une facture indique 2 400 € TTC avec TVA 20 %. Calculer le HT et la TVA.', decimals:2, answers:[{label:'Montant HT (€)', value:2000, suffix:'€'}, {label:'Montant TVA (€)', value:400, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Une chambre coûte 121 € TTC avec TVA 10 %. Quel est le prix HT ?', decimals:2, answers:[{label:'Prix HT (€)', value:110, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un produit coûte 211 € TTC avec TVA 5,5 %. Quel est le prix HT ?', decimals:2, answers:[{label:'Prix HT (€)', value:200, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un montant TTC de 719,40 € comprend une TVA à 20 %. Calculer le HT.', decimals:2, answers:[{label:'HT (€)', value:599.50, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Une prestation vaut 594 € TTC avec TVA 10 %. Calculer le HT.', decimals:2, answers:[{label:'HT (€)', value:540, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un ticket alimentaire vaut 52,75 € TTC avec TVA 5,5 %. Calculer le HT.', decimals:2, answers:[{label:'HT (€)', value:50, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un ordinateur est vendu 1 079,99 € TTC avec TVA 20 %. Calculer le prix HT.', decimals:2, answers:[{label:'Prix HT (€)', value:899.99, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un total TTC de 132 € comprend une TVA à 10 %. Calculer le montant de TVA.', decimals:2, answers:[{label:'Montant de TVA (€)', value:12, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Une facture TTC de 1 055 € comprend une TVA à 5,5 %. Calculer le montant HT.', decimals:2, answers:[{label:'Montant HT (€)', value:1000, suffix:'€'}]},
  {cat:'TTC vers HT', text:'Un produit est vendu 36 € TTC avec TVA 20 %. Calculer le montant de TVA.', decimals:2, answers:[{label:'Montant TVA (€)', value:6, suffix:'€'}]},
  {cat:'Remises successives', text:'Un fournisseur accorde 15 % puis 5 % sur un prix de 800 €. Calculer le prix final et le taux global équivalent.', decimals:2, answers:[{label:'Prix final (€)', value:646, suffix:'€'}, {label:'Taux global (%)', value:19.25, suffix:'%'}]},
  {cat:'Remises successives', text:'Trois remises successives de 10 %, 10 % et 10 % sont appliquées sur 1 000 €. Quel est le prix réellement payé ?', decimals:2, answers:[{label:'Prix payé (€)', value:729, suffix:'€'}]},
  {cat:'Remises successives', text:'Un article à 500 € subit une remise de 20 % puis une remise de 10 %. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:360, suffix:'€'}]},
  {cat:'Remises successives', text:'Un produit à 1 200 € reçoit deux remises successives de 5 % puis 8 %. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:1048.80, suffix:'€'}]},
  {cat:'Remises successives', text:'Une commande de 2 000 € reçoit 12 % puis 3 %. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:1707.20, suffix:'€'}]},
  {cat:'Remises successives', text:'Un canapé à 890 € est remisé de 30 % puis de 10 %. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:560.70, suffix:'€'}]},
  {cat:'Remises successives', text:'Un prix de 350 € reçoit 25 % puis 5 % de remise. Calculer le coefficient global.', decimals:3, answers:[{label:'Coefficient global', value:0.7125, suffix:''}]},
  {cat:'Remises successives', text:'Un prix de 350 € reçoit 25 % puis 5 % de remise. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:249.38, suffix:'€'}]},
  {cat:'Remises successives', text:'Deux remises successives de 20 % puis 20 % sont appliquées. Quel est le taux global équivalent ?', decimals:2, answers:[{label:'Taux global (%)', value:36, suffix:'%'}]},
  {cat:'Remises successives', text:'Un produit à 75 € reçoit 10 % puis 15 %. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:57.38, suffix:'€'}]},
  {cat:'Remises successives', text:'Une facture de 4 500 € bénéficie de 7 %, puis 6 %, puis 2 %. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:3855.22, suffix:'€'}]},
  {cat:'Remises successives', text:'Un article à 280 € passe par deux remises successives de 12 % et 12 %. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:216.83, suffix:'€'}]},
  {cat:'Remises successives', text:'Un article à 640 € reçoit une remise de 15 %, puis son prix remisé reçoit encore 15 %. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:462.40, suffix:'€'}]},
  {cat:'Remises successives', text:'Un tarif de 999 € est réduit de 5 % puis de 10 %. Quel est le prix final ?', decimals:2, answers:[{label:'Prix final (€)', value:854.15, suffix:'€'}]},
  {cat:'Remises successives', text:'Un prix de départ de 150 € est soumis à 40 % puis 5 % de remise. Calculer le prix final.', decimals:2, answers:[{label:'Prix final (€)', value:85.50, suffix:'€'}]},
  {cat:'Taux de variation', text:'Un article passe de 180 € à 153 €. Quel est le taux de remise accordé ?', decimals:2, answers:[{label:'Taux de remise (%)', value:15, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un tarif passe de 65 € à 71,50 €. Calculer le taux de hausse.', decimals:2, answers:[{label:'Taux de hausse (%)', value:10, suffix:'%'}]},
  {cat:'Taux de TVA', text:'Un prix TTC de 600 € correspond à un prix HT de 500 €. Retrouver le taux de TVA appliqué.', decimals:2, answers:[{label:'Taux de TVA (%)', value:20, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un prix passe de 250 € à 200 €. Calculer le taux de variation.', decimals:2, answers:[{label:'Taux de variation (%)', value:-20, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un prix passe de 80 € à 92 €. Calculer le taux de variation.', decimals:2, answers:[{label:'Taux de variation (%)', value:15, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un article passe de 120 € à 102 €. Quel est le taux de remise ?', decimals:2, answers:[{label:'Taux de remise (%)', value:15, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un abonnement passe de 29,90 € à 34,39 €. Quel est le taux de hausse ?', decimals:2, answers:[{label:'Taux de hausse (%)', value:15.02, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un prix passe de 499 € à 449,10 €. Quel est le taux de baisse ?', decimals:2, answers:[{label:'Taux de baisse (%)', value:10, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un produit passe de 40 € à 50 €. Quel est le taux de hausse ?', decimals:2, answers:[{label:'Taux de hausse (%)', value:25, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un prix passe de 1 200 € à 1 500 €. Calculer le taux de hausse.', decimals:2, answers:[{label:'Taux de hausse (%)', value:25, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un prix passe de 1 500 € à 1 200 €. Calculer le taux de baisse.', decimals:2, answers:[{label:'Taux de baisse (%)', value:20, suffix:'%'}]},
  {cat:'Taux de TVA', text:'Un prix HT de 80 € devient 88 € TTC. Quel est le taux de TVA ?', decimals:2, answers:[{label:'Taux de TVA (%)', value:10, suffix:'%'}]},
  {cat:'Taux de TVA', text:'Un prix HT de 40 € devient 42,20 € TTC. Quel est le taux de TVA ?', decimals:2, answers:[{label:'Taux de TVA (%)', value:5.5, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un article passe de 560 € à 476 €. Quel est le taux de remise ?', decimals:2, answers:[{label:'Taux de remise (%)', value:15, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un article passe de 75 € à 63,75 €. Calculer le taux de baisse.', decimals:2, answers:[{label:'Taux de baisse (%)', value:15, suffix:'%'}]},
  {cat:'Taux de variation', text:'Un produit passe de 18 € à 21,60 €. Calculer le taux de hausse.', decimals:2, answers:[{label:'Taux de hausse (%)', value:20, suffix:'%'}]},
  {cat:'Calcul complet', text:'Un article coûte 100 € HT. On applique une remise de 10 %, puis une TVA de 20 %. Quel est le prix TTC final ?', decimals:2, answers:[{label:'Prix TTC final (€)', value:108, suffix:'€'}]},
  {cat:'Calcul complet', text:'Une marchandise coûte 250 € HT. Remise 12 %, puis TVA 20 %. Calculer le TTC final.', decimals:2, answers:[{label:'TTC final (€)', value:264, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un produit vaut 89 € HT. Remise 15 %, puis TVA 5,5 %. Calculer le TTC final.', decimals:2, answers:[{label:'TTC final (€)', value:79.81, suffix:'€'}]},
  {cat:'Calcul complet', text:'Une prestation est affichée 1 000 € HT. Remise 8 %, puis TVA 10 %. Calculer le TTC final.', decimals:2, answers:[{label:'TTC final (€)', value:1012, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un produit coûte 450 € HT. Remises successives 10 % puis 5 %, puis TVA 20 %. Quel est le TTC final ?', decimals:2, answers:[{label:'TTC final (€)', value:461.70, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un meuble est affiché 780 € TTC avec TVA 20 %. Retrouver le HT, puis appliquer une remise de 10 % sur le HT. Quel est le nouveau HT ?', decimals:2, answers:[{label:'Nouveau HT (€)', value:585, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un produit à 600 € HT reçoit une remise de 20 %. Calculer le prix HT remisé puis le TTC avec TVA 20 %.', decimals:2, answers:[{label:'HT remisé (€)', value:480, suffix:'€'}, {label:'TTC final (€)', value:576, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un devis de 1 320 € TTC avec TVA 10 % reçoit ensuite une remise commerciale de 5 % sur le HT. Quel est le HT après remise ?', decimals:2, answers:[{label:'HT après remise (€)', value:1140, suffix:'€'}]},
  {cat:'Calcul complet', text:'Un prix initial de 125 € HT est augmenté de 20 % de TVA après une remise de 16 %. Calculer le TTC final.', decimals:2, answers:[{label:'TTC final (€)', value:126, suffix:'€'}]},
  {cat:'Calcul complet', text:'Une commande de 2 400 € HT obtient 7 % de remise, puis une TVA de 20 %. Calculer le montant TTC final.', decimals:2, answers:[{label:'TTC final (€)', value:2678.40, suffix:'€'}]}
];
